name: First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -  name: checkout-repo
           uses: actions/checkout@v6

        -  name: Welcome message
           run: echo "my first github workflow command"
    
        -  name: List files 
           run: ls

        -  name: Show index.html
           run: cat index.html

        -  name: create a snake
           run: cowsay -f snake "I am a python"
         